# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Tue May 24 11:14:24 2016
#      by: pyside-uic 0.2.14 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1156, 631)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.splitter_2 = QtGui.QSplitter(self.centralWidget)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter = QtGui.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.frame = QtGui.QFrame(self.splitter)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.mainPlotLabel = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.mainPlotLabel.setFont(font)
        self.mainPlotLabel.setObjectName("mainPlotLabel")
        self.verticalLayout_2.addWidget(self.mainPlotLabel)
        self.main_plot = PlotWidget(self.frame)
        self.main_plot.setObjectName("main_plot")
        self.verticalLayout_2.addWidget(self.main_plot)
        self.frame_2 = QtGui.QFrame(self.splitter)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.views_groupBox = QtGui.QGroupBox(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.views_groupBox.setFont(font)
        self.views_groupBox.setObjectName("views_groupBox")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.views_groupBox)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.cb_attempts = QtGui.QCheckBox(self.views_groupBox)
        self.cb_attempts.setObjectName("cb_attempts")
        self.verticalLayout_9.addWidget(self.cb_attempts)
        self.cb_deliveries = QtGui.QCheckBox(self.views_groupBox)
        self.cb_deliveries.setObjectName("cb_deliveries")
        self.verticalLayout_9.addWidget(self.cb_deliveries)
        self.verticalLayout_8.addWidget(self.views_groupBox)
        self.plots_groupBox = QtGui.QGroupBox(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.plots_groupBox.setFont(font)
        self.plots_groupBox.setObjectName("plots_groupBox")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.plots_groupBox)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.rb_bar = QtGui.QRadioButton(self.plots_groupBox)
        self.rb_bar.setObjectName("rb_bar")
        self.verticalLayout_10.addWidget(self.rb_bar)
        self.rb_line = QtGui.QRadioButton(self.plots_groupBox)
        self.rb_line.setObjectName("rb_line")
        self.verticalLayout_10.addWidget(self.rb_line)
        self.rb_scatter = QtGui.QRadioButton(self.plots_groupBox)
        self.rb_scatter.setObjectName("rb_scatter")
        self.verticalLayout_10.addWidget(self.rb_scatter)
        self.verticalLayout_8.addWidget(self.plots_groupBox)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem)
        self.frame_3 = QtGui.QFrame(self.splitter)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.importLabel = QtGui.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.importLabel.setFont(font)
        self.importLabel.setObjectName("importLabel")
        self.verticalLayout_7.addWidget(self.importLabel)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pb_add = QtGui.QPushButton(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pb_add.setFont(font)
        self.pb_add.setObjectName("pb_add")
        self.horizontalLayout_4.addWidget(self.pb_add)
        self.pb_remove = QtGui.QPushButton(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pb_remove.setFont(font)
        self.pb_remove.setObjectName("pb_remove")
        self.horizontalLayout_4.addWidget(self.pb_remove)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.infusionLabel = QtGui.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.infusionLabel.setFont(font)
        self.infusionLabel.setObjectName("infusionLabel")
        self.verticalLayout_7.addWidget(self.infusionLabel)
        self.list_files = QtGui.QListWidget(self.frame_3)
        self.list_files.setObjectName("list_files")
        self.verticalLayout_7.addWidget(self.list_files)
        self.frame_4 = QtGui.QFrame(self.splitter_2)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tab_distributions = QtGui.QTabWidget(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tab_distributions.setFont(font)
        self.tab_distributions.setObjectName("tab_distributions")
        self.tab_1 = QtGui.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.zoom_plot = PlotWidget(self.tab_1)
        self.zoom_plot.setObjectName("zoom_plot")
        self.verticalLayout.addWidget(self.zoom_plot)
        self.tab_distributions.addTab(self.tab_1, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.graphicsView = PlotWidget(self.tab_2)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout_3.addWidget(self.graphicsView)
        self.tab_distributions.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.graphicsView_2 = PlotWidget(self.tab_3)
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.verticalLayout_4.addWidget(self.graphicsView_2)
        self.tab_distributions.addTab(self.tab_3, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.graphicsView_3 = PlotWidget(self.tab_4)
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.verticalLayout_11.addWidget(self.graphicsView_3)
        self.tab_distributions.addTab(self.tab_4, "")
        self.horizontalLayout_3.addWidget(self.tab_distributions)
        self.scrollArea = QtGui.QScrollArea(self.frame_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(450, 0))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 448, 238))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tableLabel = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tableLabel.setFont(font)
        self.tableLabel.setObjectName("tableLabel")
        self.verticalLayout_6.addWidget(self.tableLabel)
        self.tb_stats = QtGui.QTableWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tb_stats.sizePolicy().hasHeightForWidth())
        self.tb_stats.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tb_stats.setFont(font)
        self.tb_stats.setObjectName("tb_stats")
        self.tb_stats.setColumnCount(0)
        self.tb_stats.setRowCount(0)
        self.verticalLayout_6.addWidget(self.tb_stats)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_3.addWidget(self.scrollArea)
        self.verticalLayout_5.addWidget(self.splitter_2)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1156, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.menuBar.setFont(font)
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtGui.QMenu(self.menuBar)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.menuFile.setFont(font)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtGui.QMenu(self.menuBar)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.menuView.setFont(font)
        self.menuView.setObjectName("menuView")
        self.menuHelp = QtGui.QMenu(self.menuBar)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.menuHelp.setFont(font)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tab_distributions.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.mainPlotLabel.setText(QtGui.QApplication.translate("MainWindow", "PCA Usage", None, QtGui.QApplication.UnicodeUTF8))
        self.views_groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Views", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_attempts.setText(QtGui.QApplication.translate("MainWindow", "Attempts", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_deliveries.setText(QtGui.QApplication.translate("MainWindow", "Deliveries", None, QtGui.QApplication.UnicodeUTF8))
        self.plots_groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Plot Types", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_bar.setText(QtGui.QApplication.translate("MainWindow", "Bar", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_line.setText(QtGui.QApplication.translate("MainWindow", "Line", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_scatter.setText(QtGui.QApplication.translate("MainWindow", "Scatter", None, QtGui.QApplication.UnicodeUTF8))
        self.importLabel.setText(QtGui.QApplication.translate("MainWindow", "Import Infusion Identifiers and Data", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_add.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_remove.setText(QtGui.QApplication.translate("MainWindow", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.infusionLabel.setText(QtGui.QApplication.translate("MainWindow", "Infusion Identifiers", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_distributions.setTabText(self.tab_distributions.indexOf(self.tab_1), QtGui.QApplication.translate("MainWindow", "Main Plot Zoom View", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_distributions.setTabText(self.tab_distributions.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Attempts Distribution", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_distributions.setTabText(self.tab_distributions.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Deliveries Distribution", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_distributions.setTabText(self.tab_distributions.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "Rest Distribution", None, QtGui.QApplication.UnicodeUTF8))
        self.tableLabel.setText(QtGui.QApplication.translate("MainWindow", "Summary Statistics", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("MainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))

from pyqtgraph import PlotWidget
